TICKERS=BTC/USD,ETH/USD #FAKEPACA
FEED=trades,quotes
ENDPOINT=/v1beta3/crypto/us
url=`:wss://stream.data.alpaca.markets:443
AUTO_START=1
ALPACA_KEY=PKPHWIVR6N4YU2ON2D5TJDYWB6
ALPACA_SECRET=5HMBNJhRruFq7gBMLrDQuQ3k8xtVbwnxYk44BUBAiMTD
ALPACA_HDB=